created Testimonials model 1
deco-sites/fashion pull request #236
Opened 2023-05-20 16:38 UTC by EversonDias

## Qual a section que voce esta fazendo?

## Checklist

- [ ] Estou usando tokens do DaisyUI e Tailwind CSS
- [ ] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ ] O componente esta editável no admin da Deco
- [ ] Adicionei link de preview da section do admin da deco no PR
- [ ] Minha section funciona com propriedades padrão
- [ ] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:04 UTC, jovenan requested changes
Ola, você precisa adicionar o link da library para conseguirmos testar e fez alterações em outros arquivos que não poderiam. Corrija esses pontos para que possamos seguir com a aprovação.

2023-05-21 12:56 UTC, eduardobbrito requested changes
Você está quase lá! Para ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-21 12:56 UTC, eduardobbrito commented on sections/FAQ/FAQ-model-1.diasdev.tsx
> +export interface Props {
Esse componente FAQ, pretendia que ele fosse avaliado também? Caso sim, cria um novo PR pra ele, caso contrário, remove esse arquivo por favor

2023-05-21 12:56 UTC, eduardobbrito commented on sections/Testimonials/logo-deco-testimonial.svg
Esses arquivos de ícones, o ideal é usarmos as opções disponíveis na própria library da deco em deco-sites/std. Não é necessário importá-los aqui pro PR.

2023-05-21 12:56 UTC, eduardobbrito commented on sections/Testimonials/Testimonial-model-2.diasdev.tsx
> +          Testimonials
Aqui também poderia ser customizável!

2023-05-21 12:56 UTC, eduardobbrito commented on sections/Testimonials/Testimonials-model-1.diasdev.tsx
> +      <div className="flex flex-col md:grid md:grid-cols-3">
Bom uso das classes e props! Uma melhoria que acho que vale a pena é pensar nos casos onde haja menos de 3 depoimentos e como ficaria o espaçamento desse conteúdo.

![image](https://github.com/deco-sites/fashion/assets/26016127/1b27d00d-6f50-4997-a171-9d00a8e467db)

2023-06-30 13:07 UTC, closed without merging