Implements QuickView section - Luminosity
deco-sites/fashion pull request #245
Opened 2023-05-20 18:49 UTC by darllinsonazvd

## Qual a section que voce esta fazendo?

Figma: https://www.figma.com/file/T4oBjZSaiahuqaAQA8ihls/Deco-Hackathon-III-%E2%80%A2--Blocks-Library?type=design&node-id=329-33636&t=qsAc15NqOxZToxiQ-0

Admin: https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL1F1aWNrVmlld3MvUXVpY2tWaWV3Lkx1bWlub3NpdHkudHN4&type=QuickViews

## Checklist

- [ x ] Estou usando tokens do DaisyUI e Tailwind CSS
- [ x ] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ x ] O componente esta editável no admin da Deco
- [ x ] Adicionei link de preview da section do admin da deco no PR
- [ x ] Minha section funciona com propriedades padrão
- [ x ] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:35 UTC, Steffany-Martins requested changes
O link do preview do bloco não está na descrição. Poderia colocar, por favor @darllinsonazvd

2023-05-20 22:36 UTC, igorbrasileiro commented on sections/QuickViews/QuickView.Luminosity.tsx
> +          <div className="absolute bottom-2 left-2 w-fit px-2 py-1 bg-[#E37A69] lg:bottom-[90%]">
token hard coded

2023-05-20 22:38 UTC, igorbrasileiro commented on sections/QuickViews/QuickView.Luminosity.tsx
> +                R$ {promotionalPrice.toLocaleString("pt-br", {
lang hard coded

2023-05-20 22:40 UTC, igorbrasileiro commented on sections/QuickViews/QuickView.Luminosity.tsx
> +  const [itemQuantity, setItemQuantity] = useState<number>(0);
Não funciona client-side, pois não é uma ilha

2023-05-20 22:41 UTC, igorbrasileiro commented on sections/QuickViews/QuickView.Luminosity.tsx
> +import { useState } from "preact/hooks";
Não funciona client-side

2023-05-20 22:43 UTC, igorbrasileiro requested changes
Você está quase lá! Para avançar para a próxima etapa e ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-20 22:44 UTC, Steffany-Martins commented on sections/QuickViews/QuickView.Luminosity.tsx
> +  productsImages: Array<{ url: string; alt: string }>;
A props de url não é pra ser alterada com o ''link'' do produto. Precisa ser com o type Image que nem usamos na fashion:
https://github.com/deco-sites/fashion/blob/main/components/ui/BannerCarousel.tsx

2023-05-20 22:59 UTC, darllinsonazvd commented
alterações implementadas!

2023-05-20 22:59 UTC, darllinsonazvd commented
> O link do preview do bloco não está na descrição. Poderia colocar, por favor @darllinsonazvd

é só copiar a url na barra de endereços do browser?

2023-05-20 23:48 UTC, Steffany-Martins commented
> > O link do preview do bloco não está na descrição. Poderia colocar, por favor @darllinsonazvd
> 
> é só copiar a url na barra de endereços do browser?

Isso! Copia no preview no bloco que está testando

2023-05-21 01:27 UTC, darllinsonazvd commented
> > > O link do preview do bloco não está na descrição. Poderia colocar, por favor @darllinsonazvd
> > 
> > 
> > é só copiar a url na barra de endereços do browser?
> 
> Isso! Copia no preview no bloco que está testando

já havia feito isso, inclusive fiz o teste antes de enviar a PR 🤔
agora não mais acesso ao site no admin da deco, infelizmente :(
não tem como copiar o código e testar manualmente, garanto que essa section ficou mt dahora 🥲

2023-06-06 22:19 UTC, closed without merging