Cookies Consent
deco-sites/fashion pull request #248
Opened 2023-05-20 18:50 UTC by pedrosqra

## Qual a section que voce esta fazendo? 

Categoria 3 - Cookies Consent

Deco:
https://deco.cx/admin/239/pages/15492?pagePath=%252F%253F_cache%253D1684608572820%2526pageId%253D15492&sort=asc%3Apath&state=published%2Cdraft&sectionId=deco-sites%2Ffashion%2Fsections%2FCookieConsent.tsx-10

Figma - Desktop 3 foi usado de inspiração:
https://www.figma.com/file/T4oBjZSaiahuqaAQA8ihls/Deco-Hackathon-III-%E2%80%A2--Blocks-Library?type=design&node-id=329-25733&t=jAfpkdBtymOorG3V-0

## Checklist

- [ x] Estou usando tokens do DaisyUI e Tailwind CSS
- [ x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ x] O componente esta editável no admin da Deco
- [ x] Adicionei link de preview da section do admin da deco no PR
- [ x] Minha section funciona com propriedades padrão
- [ x] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 21:42 UTC, pedrosqra commented
Pronto

2023-05-21 00:26 UTC, Steffany-Martins requested changes
O componente não possui props, é preciso ser editável na deco: links, textos e até textos de botões, ícones etc. Verifica o ponto que te pedi 👍🏿

2023-05-21 00:26 UTC, Steffany-Martins commented on components/ui/CookieConsent.tsx
>          class="transform-gpu translate-y-[200%] transition fixed bottom-0 sm:bottom-4 w-screen z-50"
Tem estilo hard codded, por favor trocar pelas classes do tailwind ou daisy UI. Você pode aproximar 200% por exemplo ou checar se tem algo compatível.

2023-05-21 06:53 UTC, pedrosqra commented on components/ui/CookieConsent.tsx
>          class="transform-gpu translate-y-[200%] transition fixed bottom-0 sm:bottom-4 w-screen z-50"
Adicionei props e tentei fazer as alterações no tailwind e acho que funcionou, só que essa parte do design eu achei que a gente ia apenas se inspirar em uma variação do figma, não reproduzir ela completamente 😮😢

2023-06-30 13:07 UTC, closed without merging