feat: CookieConsentSection
deco-sites/fashion pull request #253
Opened 2023-05-20 19:21 UTC by IagoGoncalves

## Qual a section que voce esta fazendo?
Cookie Consent
https://deco.cx/admin/sites/fashion/blocks/CookieConsent-time66?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL0Nvb2tpZS9Db29raWVDb25zZW50LnRpbWUtNjYudHN4&type=Cookie

## Checklist

- [X] Estou usando tokens do DaisyUI e Tailwind CSS
- [ ] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ ] O componente esta editável no admin da Deco
- [X] Adicionei link de preview da section do admin da deco no PR
- [X] Minha section funciona com propriedades padrão
- [ ] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 19:22 UTC, IagoGoncalves commented
Ainda não finalizado

2023-05-20 19:28 UTC, IagoGoncalves commented
Finalizado

2023-05-21 13:28 UTC, eduardobbrito requested changes
Você está quase lá! Para ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas e finalize as tarefas restantes na checkbox como deixar o componente editável no CMS.

2023-05-21 13:28 UTC, eduardobbrito commented on sections/Cookie/CookieConsent.time-66.tsx
> +              <svg
Os SVGs podem ser importados através do componente de Icon da deco-sites/std!

2023-06-30 13:06 UTC, closed without merging