FAQ - Section 3 - TIME 233
deco-sites/fashion pull request #276
Opened 2023-05-20 20:45 UTC by PatrickalKhouri

## Qual a section que voce esta fazendo?

Section 3 - Easy - FAQ

## Checklist

- [ok] Estou usando tokens do DaisyUI e Tailwind CSS
- [ ok] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ ok] O componente esta editável no admin da Deco
- [ok ] Adicionei link de preview da section do admin da deco no PR
- [ok] Minha section funciona com propriedades padrão
- [ Nao fiz variações] Adicionei links das variacoes do figma que fiz no PR

Link preview:

https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL0ZhcS50c3g%3D&type=sections

2023-05-20 21:22 UTC, PatrickalKhouri commented
Pronto

2023-05-21 13:12 UTC, eduardobbrito requested changes
Você está quase lá! Para ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-21 13:12 UTC, eduardobbrito commented on package-lock.json
Remover esse arquivo por favor!

2023-05-21 13:12 UTC, eduardobbrito commented on deno.json
Essa alteração, você entende que deve ser enviada pra produção também? Se for algo que não é necessário ao PR, é melhor remover!

2023-05-21 13:12 UTC, eduardobbrito commented on components/faq/BottomPart.tsx
> +      {/* Mobile Version */}
Renderizar um componente diferente pra mobile e desktop acaba enviando mais código ao browser do que o necessário. O ideal é fazer um único componente que possa se adaptar aos designs necessários apenas com classes, desse jeito o componente fica mais performático e adaptável!

2023-05-21 13:28 UTC, PatrickalKhouri commented on deno.json
Eu nao mexi nela achei que era algo que vinha junto, vou remover

2023-05-21 13:28 UTC, PatrickalKhouri commented on components/faq/BottomPart.tsx
> +      {/* Mobile Version */}
Eu tava fazendo isso quando deu aquele erro de rota ai para entregar eu acabei nao adaptando. Eu lembro que testei e nos componentes eu nao precisava pq tava funcionando redondo. Vou remover

2023-05-21 13:43 UTC, PatrickalKhouri commented on components/faq/BottomPart.tsx
> +      {/* Mobile Version */}
Eduardo, foi removido do deco/admin o fashion ai n consigo testar. Eu to com as atlterações na agulha aqui, tem como botar pra mim de novo eu testo rapidinho e ai vcs removem?

2023-05-21 13:48 UTC, eduardobbrito commented on components/faq/BottomPart.tsx
> +      {/* Mobile Version */}
Opa Patrick, os acessos ao admin foram removidos na organização que a equipe fez durante a Hackathon. Por enquanto, pode seguir o desenvolvimento pelo localhost? De todo modo, não interfere na sua classificação no evento 😄

2023-06-30 13:07 UTC, closed without merging