feat: creates Shortcut component
deco-sites/fashion pull request #286
Opened 2023-05-20 21:09 UTC by NicolasOliveira861

## Qual a section que voce esta fazendo?

Fiz o componente de shortcuts

Link da Preview: https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL1Nob3J0Y3V0cy9TaG9ydGN1dHMuMzUudHN4&type=Shortcuts

## Checklist

- [X] Estou usando tokens do DaisyUI e Tailwind CSS
- [X] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [X] O componente esta editável no admin da Deco
- [X] Adicionei link de preview da section do admin da deco no PR
- [X] Minha section funciona com propriedades padrão
- [] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 21:46 UTC, igorbrasileiro commented on components/ui/Shortcuts.tsx
Olá, poderia mover este componente para dentro da section criada?

2023-05-20 21:47 UTC, igorbrasileiro commented on components/ui/Features.tsx
Poderia remover os arquivos que você não deseja alterar? Para evitar problemas durante o merge

2023-05-20 21:49 UTC, igorbrasileiro requested changes
Parabéns, você passou!
Poderia só mover o componente de Shortcuts para dentro da sua section.

2023-05-20 22:02 UTC, NicolasOliveira861 commented on components/ui/Shortcuts.tsx
Alterei lá

2023-05-21 15:14 UTC, igorbrasileiro commented on sections/Shortcuts/Shortcuts.35.tsx
> +export { default } from "./Shortcuts.tsx";
```suggestion
import Icon from "$store/components/ui/Icon.tsx";

export interface ShortcutProps {
  link: string;
  text: string;
}

export interface Props {
  whatsapp: ShortcutProps;
  sms: ShortcutProps;
  ruler: ShortcutProps;
  delivery: ShortcutProps;
  exchange: ShortcutProps;
  direction: "left" | "right";
}

function Shortcut(
  {
    delivery = { link: "/", text: "Delivery" },
    exchange = { link: "/", text: "Exchange" },
    ruler = { link: "/", text: "Ruler" },
    sms = { link: "/", text: "SMS" },
    whatsapp = { link: "/", text: "Whatsapp" },
    direction = "right",
  }: Props,
) {
  return (
    <div
      className={`border-[1px] border-[#AAAAAA] fixed ${
        direction === "left" ? "left-0" : "right-0"
      } top-1/2 -translate-1/2 flex flex-col bg-white`}
    >
      <a
        href={whatsapp.link}
        data-tip={whatsapp.text}
        className="p-2 border-b-[#AAAAAA] border-b-[1px] tooltip tooltip-left"
      >
        <Icon id="WhatsApp" size={24} />
      </a>

      <a
        href={sms.link}
        data-tip={sms.text}
        className="p-2 border-b-[#AAAAAA] border-b-[1px] tooltip tooltip-left"
      >
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M7 6C6.46957 6 5.96086 6.21071 5.58579 6.58579C5.21071 6.96086 5 7.46957 5 8V18.5858L7.29289 16.2929C7.48043 16.1054 7.73478 16 8 16H17C17.5304 16 18.0391 15.7893 18.4142 15.4142C18.7893 15.0391 19 14.5304 19 14V8C19 7.46957 18.7893 6.96086 18.4142 6.58579C18.0391 6.21071 17.5304 6 17 6H7ZM4.17157 5.17157C4.92172 4.42143 5.93913 4 7 4H17C18.0609 4 19.0783 4.42143 19.8284 5.17157C20.5786 5.92172 21 6.93913 21 8V14C21 15.0609 20.5786 16.0783 19.8284 16.8284C19.0783 17.5786 18.0609 18 17 18H8.41421L4.70711 21.7071C4.42111 21.9931 3.99099 22.0787 3.61732 21.9239C3.24364 21.7691 3 21.4045 3 21V8C3 6.93913 3.42143 5.92172 4.17157 5.17157ZM7 9C7 8.44772 7.44772 8 8 8H16C16.5523 8 17 8.44772 17 9C17 9.55228 16.5523 10 16 10H8C7.44772 10 7 9.55228 7 9ZM7 13C7 12.4477 7.44772 12 8 12H14C14.5523 12 15 12.4477 15 13C15 13.5523 14.5523 14 14 14H8C7.44772 14 7 13.5523 7 13Z"
            fill="#292929"
          />
        </svg>
      </a>

      <a
        href={ruler.link}
        type="button"
        data-tip={ruler.text}
        className="p-2 border-b-[#AAAAAA] border-b-[1px] tooltip tooltip-left"
      >
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M16.2929 2.29289C16.6834 1.90237 17.3166 1.90237 17.7071 2.29289L21.7071 6.29289C22.0976 6.68342 22.0976 7.31658 21.7071 7.70711L7.70711 21.7071C7.31658 22.0976 6.68342 22.0976 6.29289 21.7071L2.29289 17.7071C1.90237 17.3166 1.90237 16.6834 2.29289 16.2929L4.79269 13.7931L13.7927 4.7931L16.2929 2.29289ZM14.5 6.91421L15.2929 7.70711C15.6834 8.09763 16.3166 8.09763 16.7071 7.70711C17.0976 7.31658 17.0976 6.68342 16.7071 6.29289L15.9142 5.5L17 4.41421L19.5858 7L7 19.5858L4.41421 17L5.5 15.9142L6.29289 16.7071C6.68342 17.0976 7.31658 17.0976 7.70711 16.7071C8.09763 16.3166 8.09763 15.6834 7.70711 15.2929L6.91421 14.5L8.5 12.9142L9.29289 13.7071C9.68342 14.0976 10.3166 14.0976 10.7071 13.7071C11.0976 13.3166 11.0976 12.6834 10.7071 12.2929L9.91421 11.5L11.5 9.91421L12.2929 10.7071C12.6834 11.0976 13.3166 11.0976 13.7071 10.7071C14.0976 10.3166 14.0976 9.68342 13.7071 9.29289L12.9142 8.5L14.5 6.91421Z"
            fill="#292929"
          />
        </svg>
      </a>

      <a
        href={delivery.link}
        data-tip={delivery.text}
        className="p-2 border-b-[#AAAAAA] border-b-[1px] tooltip tooltip-left"
      >
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M1.1001 4.99998C1.1001 4.50292 1.50304 4.09998 2.0001 4.09998H13.0001C13.4972 4.09998 13.9001 4.50292 13.9001 4.99998V5.09998H18.0001C18.3162 5.09998 18.6092 5.26584 18.7718 5.53693L21.7718 10.5369C21.8558 10.6768 21.9001 10.8369 21.9001 11V17C21.9001 17.497 21.4972 17.9 21.0001 17.9H19.7577C19.3791 19.061 18.2876 19.9 17.0001 19.9C15.7126 19.9 14.6211 19.061 14.2425 17.9H9.75773C9.37906 19.061 8.28755 19.9 7.0001 19.9C5.71264 19.9 4.62114 19.061 4.24246 17.9H3.0001C2.50304 17.9 2.1001 17.497 2.1001 17V13C2.1001 12.5029 2.50304 12.1 3.0001 12.1C3.49715 12.1 3.9001 12.5029 3.9001 13V16.1H4.24246C4.62114 14.9389 5.71264 14.1 7.0001 14.1C8.28755 14.1 9.37906 14.9389 9.75773 16.1H12.1001V5.89998H2.0001C1.50304 5.89998 1.1001 5.49703 1.1001 4.99998ZM13.9001 6.89998V10.1H19.4105L17.4905 6.89998H13.9001ZM20.1001 11.9H13.9001V16.1H14.2425C14.6211 14.9389 15.7126 14.1 17.0001 14.1C18.2876 14.1 19.3791 14.9389 19.7577 16.1H20.1001V11.9ZM2.1001 8.99997C2.1001 8.50292 2.50304 8.09997 3.0001 8.09997H7.0001C7.49715 8.09997 7.9001 8.50292 7.9001 8.99997C7.9001 9.49703 7.49715 9.89997 7.0001 9.89997H3.0001C2.50304 9.89997 2.1001 9.49703 2.1001 8.99997ZM7.0001 15.9C6.39258 15.9 5.9001 16.3925 5.9001 17C5.9001 17.6075 6.39258 18.1 7.0001 18.1C7.60761 18.1 8.1001 17.6075 8.1001 17C8.1001 16.3925 7.60761 15.9 7.0001 15.9ZM17.0001 15.9C16.3926 15.9 15.9001 16.3925 15.9001 17C15.9001 17.6075 16.3926 18.1 17.0001 18.1C17.6076 18.1 18.1001 17.6075 18.1001 17C18.1001 16.3925 17.6076 15.9 17.0001 15.9Z"
            fill="#292929"
          />
        </svg>
      </a>

      <a
        href={exchange.link}
        data-tip={exchange.text}
        className="p-2 tooltip tooltip-left"
      >
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M17.3637 3.36358C17.7152 3.01211 18.285 3.01211 18.6365 3.36358L21.6365 6.36358C21.988 6.71505 21.988 7.2849 21.6365 7.63637L18.6365 10.6364C18.285 10.9878 17.7152 10.9878 17.3637 10.6364C17.0122 10.2849 17.0122 9.71505 17.3637 9.36358L18.8273 7.89998H3.0001C2.50304 7.89998 2.1001 7.49703 2.1001 6.99998C2.1001 6.50292 2.50304 6.09998 3.0001 6.09998H18.8273L17.3637 4.63637C17.0122 4.2849 17.0122 3.71505 17.3637 3.36358ZM6.63649 13.3636C6.98797 13.7151 6.98797 14.2849 6.63649 14.6364L5.17289 16.1H21.0001C21.4972 16.1 21.9001 16.5029 21.9001 17C21.9001 17.497 21.4972 17.9 21.0001 17.9H5.17289L6.63649 19.3636C6.98797 19.715 6.98797 20.2849 6.63649 20.6364C6.28502 20.9878 5.71517 20.9878 5.3637 20.6364L2.3637 17.6364C2.01223 17.2849 2.01223 16.715 2.3637 16.3636L5.3637 13.3636C5.71517 13.0121 6.28502 13.0121 6.63649 13.3636Z"
            fill="#292929"
          />
        </svg>
      </a>
    </div>
  );
}

export default Shortcut;
```

2023-05-21 15:15 UTC, igorbrasileiro commented on sections/Shortcuts/Shortcuts.tsx
Remove este componente

2023-06-30 13:07 UTC, closed without merging