[Time 187] Campaign Timer
deco-sites/fashion pull request #294
Opened 2023-05-20 21:29 UTC by caiocavalcante063

## Qual a section que voce esta fazendo?

## Checklist

- [x] Estou usando tokens do DaisyUI e Tailwind CSS
- [x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [x] O componente esta editável no admin da Deco
- [x] Adicionei link de preview da section do admin da deco no PR
- [x] Minha section funciona com propriedades padrão
- [x] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 21:40 UTC, caiocavalcante063 commented
Pronto

2023-05-21 01:42 UTC, lucis requested changes
Você está quase lá! Para avançar para a próxima etapa e ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-21 01:42 UTC, lucis commented on islands/CampaignTimer.tsx
> +      }
O usuário que configura um timer não deveria configurar o tempo que falta, isso é o que o código deveria calcular.

Deveria ser a data final, não?

2023-05-21 01:42 UTC, lucis commented on islands/CampaignTimer.tsx
> +        <div class="col-span-1 flex flex-col h-auto w-full  bg-[#E37A69] text-white items-center p-4">
BG com cor especifica

2023-05-21 01:42 UTC, lucis commented on islands/CampaignTimer.tsx
> +                        <div class="numero">{formattedTime.minutes}</div>
Por que a classe `numero`?

2023-05-21 01:42 UTC, lucis commented on islands/CampaignTimer.tsx
> +                    <button onClick={() => handleLinkClick(buttonLink)}class="bg-[#273746] p-2 right-0 h-full">{buttonText}</button>
BG com cor fixa

2023-05-21 01:42 UTC, lucis commented on islands/CampaignTimer.tsx
> +                                <div class='flex font-normal text-sm-standard items-center'>
```suggestion
                                <div class="flex font-normal text-sm-standard items-center">
```

2023-06-30 13:09 UTC, closed without merging