[TIME 176] feat: Campaign Timer
deco-sites/fashion pull request #295
Opened 2023-05-20 21:30 UTC by arthursacurai3

## Qual a section que voce esta fazendo?

link da variaçao: 
https://www.figma.com/file/T4oBjZSaiahuqaAQA8ihls/Deco-Hackathon-III-%E2%80%A2--Blocks-Library?type=design&node-id=329-24073&t=dk4joCKw0bJi8RYO-0

link do preview: 
https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL0hlYWRlci50c3g%3D&type=sections

## Checklist

- [ x] Estou usando tokens do DaisyUI e Tailwind CSS
- [ x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ x] O componente esta editável no admin da Deco
- [ x] Adicionei link de preview da section do admin da deco no PR
- [ x] Minha section funciona com propriedades padrão
- [ x] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:31 UTC, arthursacurai3 commented
esqueci de remover os dados chumbados hehe
o correto é o componente CapaignTimer no header estar assim:
`            <CampaignTimer
              campaign_data={campaignTimerProps.campaign_data}
            />`

2023-05-21 12:53 UTC, MatheusTrindade5201 commented on components/header/Header.tsx
> +  };
Esse tipo de valor dever ser recebido vindo das props do Admin, e caso não se receba nada lá, ter um valor padrão

2023-05-21 12:54 UTC, MatheusTrindade5201 commented on components/header/Header.tsx
> +
A ideia é que esse componente não seja chamado no Header, e sim que seja uma section independente, que possa ser adicionada pelo Admin em qualquer lugar da página

2023-05-21 12:55 UTC, MatheusTrindade5201 commented on components/header/CampaignTimer.tsx
> +  { campaign_data }: CampaignTimerProps,
Os valores padrões entrariam aqui: 
function CampaignTimer(
  { campaign_data = {valores padrões} }: CampaignTimerProps,

2023-05-21 12:57 UTC, MatheusTrindade5201 requested changes
Você está quase lá! Para ter seu componente usado por todos, por favor complete as mudanças pedidas.

2023-06-30 13:09 UTC, closed without merging