[TIME 18]
deco-sites/fashion pull request #298
Opened 2023-05-20 21:40 UTC by LuanaMayumi

## Qual a section que voce esta fazendo?

## Checklist

- [x] Estou usando tokens do DaisyUI e Tailwind CSS
- [x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [x] O componente esta editável no admin da Deco
- [ ] Adicionei link de preview da section do admin da deco no PR
- [x] Minha section funciona com propriedades padrão
- [ ] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 21:47 UTC, elitonrosa commented
Pronto!

2023-05-21 09:29 UTC, mcandeia requested changes
Lembre-se de corrigir o espaçamento entre o texto e os campos, eles estão levemente diferente do figma.

Você está quase lá! Para avançar para a próxima etapa e ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-21 09:29 UTC, mcandeia commented on sections/Auth/Auth.codersT27.tsx
> +            Lorem ipsum dolor sit amet consectetur adipisicing elit.
O ideal é que isso seja editável pelo usuário, e que seja recebido como props

2023-05-21 09:29 UTC, mcandeia commented on sections/Auth/Auth.codersT27.tsx
> +          <p>Email</p>
```suggestion
          <p>E-mail</p>
```

2023-05-21 09:29 UTC, mcandeia commented on sections/Auth/Auth.codersT27.tsx
> +          </p>
todos os links devem ser recebidos como propriedades. Lembre-se sempre de usar valores padrões

2023-05-21 09:29 UTC, mcandeia commented on sections/Newsletter/Newsletter.codersT27.tsx
> +        </p>
receber links como props

2023-05-21 09:32 UTC, mcandeia requested changes
Também notei que seus tokens de CSS são todos hardcoded, exemplos:

- bg-[#273746]
- bg-[#273746] 
- text-[#FFFFFF] 
- hover:bg-[#293e52]

Todos devem ser usados a partir das cores primárias,

exemplo: bg-primary, bg-secondary, etc

2023-06-04 21:30 UTC, closed without merging