MasRap dev Time 237
deco-sites/fashion pull request #323
Opened 2023-05-20 21:58 UTC by Samuellucas007

## Qual a section que voce esta fazendo?

## Checklist

- [x] Estou usando tokens do DaisyUI e Tailwind CSS
- [x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [x] O componente esta editável no admin da Deco
- [x] Adicionei link de preview da section do admin da deco no PR
- [x] Minha section funciona com propriedades padrão

login: https://deco-sites-masrap.deno.dev/live/previews/15943
signin: deco-sites-masrap.deno.dev/live/previews/15945
ImageGallery: deco-sites-masrap.deno.dev/live/previews/15947
Contact: deco-sites-masrap.deno.dev/live/previews/15946

2023-05-20 22:04 UTC, Samuellucas007 commented
Caminho do import menu no arquivo Header.tsx esta incorreto. mas o codigo esta funcionando.
caminho do import correto: import Menu from "./Menu.tsx";

2023-05-21 00:21 UTC, Steffany-Martins requested changes
Os componentes não estão usando o princípio de Design First e não tem valores defaults nas props. Por favor, checar principalmente a performance dos componentes e se está responsivo em Mobile e Desktop. E também as imagens estão esticadas.

2023-05-21 00:21 UTC, Steffany-Martins commented on components/auth/login.tsx
> +          <h1 class="text-[#292929] text-[48px]">Log in</h1>
Muitas classes hard codded , trocar para classes do tailwind/daisy UI.

2023-05-21 07:09 UTC, Samuellucas007 commented on components/auth/login.tsx
> +          <h1 class="text-[#292929] text-[48px]">Log in</h1>
Realizei algumas alterações.

2023-06-30 13:06 UTC, closed without merging