Discount banner - Time #250
deco-sites/fashion pull request #327
Opened 2023-05-20 21:59 UTC by karenaciole

## Qual a section que voce esta fazendo?

## Checklist

- [X ] Estou usando tokens do DaisyUI e Tailwind CSS
- [X] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [X] O componente esta editável no admin da Deco
- [X] Adicionei link de preview da section do admin da deco no PR
- [X] Minha section funciona com propriedades padrão
- [ ] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:18 UTC, karenaciole commented
Acabei enviando o PR vazio, tive uns problemas no commit do arquivo. :(

2023-05-21 01:50 UTC, lucis requested changes
Você está quase lá! Para avançar para a próxima etapa e ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-21 01:50 UTC, lucis commented on .github/pull_request_template.md
> +## Qual a section que voce esta fazendo?
Não dá pra trocar o item pelas setas

![image](https://github.com/deco-sites/fashion/assets/18706156/06730064-33ff-4c6d-a7c4-0db455b60f5c)

2023-05-21 01:50 UTC, lucis commented on sections/DiscountBanner/DiscountBanner.Porral_28.5.tsx
> +                  Button
Texto do botão deveria ser configurável

2023-05-21 01:50 UTC, lucis commented on sections/DiscountBanner/DiscountBanner.Porral_28.5.tsx
> +              <button class="bg-cyan-950 text-white ml-4">
Cores não deveriam ser fixes

2023-06-30 13:06 UTC, closed without merging