Alice e Alan
deco-sites/fashion pull request #328
Opened 2023-05-20 22:00 UTC by AlanVncs

## Qual a section que voce esta fazendo?

Cookie Consent
https://www.figma.com/file/hKbkZVTBQsjk83R5xH5Hd5/Deco-Hackathon-III-%E2%80%A2--Blocks-Library-(Copy)?type=design&node-id=12-79256&t=aduYuwXORc17HXPz-0

FAQ
https://www.figma.com/file/hKbkZVTBQsjk83R5xH5Hd5/Deco-Hackathon-III-%E2%80%A2--Blocks-Library-(Copy)?type=design&node-id=333-23153&t=aduYuwXORc17HXPz-0

Admin:
https://deco.cx/admin/239/pages/15694?pagePath=%252F%253F_cache%253D1684619796929%2526pageId%253D15694&sort=asc%3Apath&state=published%2Cdraft&sectionId=.%2Fsections%2FFAQ%2FFAQ.alan-alice.tsx-5878

## Checklist

- [x] Estou usando tokens do DaisyUI e Tailwind CSS
- [x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [x] O componente esta editável no admin da Deco
- [x] Adicionei link de preview da section do admin da deco no PR
- [x] Minha section funciona com propriedades padrão
- [x] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:28 UTC, AlanVncs commented
**Correção**
**Página de admin**: https://deco.cx/admin/239/pages/15954

2023-05-21 13:08 UTC, MatheusTrindade5201 commented on sections/CookieConsent/CookieConsent.alan-alice.tsx
> +};
A Deco tem um SVG que pode ser usado tanto para a seta quanto para o x, basta importar o componente:

`import Icon from "$store/components/ui/Icon.tsx";`

E usar da seguinte forma: 

`<Icon size={20} id="ChevronDown" strokeWidth={3} />`

O id define o svg que sera usado

2023-05-21 13:09 UTC, MatheusTrindade5201 commented on sections/CookieConsent/CookieConsent.alan-alice.tsx
> +}
As props devem ser exportadas com o npme Props, para serem visualizadas no admin e permitir a edição

2023-05-21 13:10 UTC, MatheusTrindade5201 commented on sections/CookieConsent/CookieConsent.alan-alice.tsx
> +      class={"bg-white fixed z-10 bottom-4 left-1/2 -translate-x-1/2 w-[calc(100%-32px)] max-w-[480px] p-4 border border-[#f8f8f8] shadow-lg md:p-6"}
Por favor, trocar as cores hard-coded, como o border-[#f8f8f8f], por tokens DaisyUI

2023-05-21 13:13 UTC, MatheusTrindade5201 commented on sections/FAQ/FAQ.alan-alice.tsx
> +}
Mesmo comentário do CookieConsent, as props devem ter o nome Props

2023-05-21 13:15 UTC, MatheusTrindade5201 commented on sections/FAQ/FAQ.alan-alice.tsx
> +          <p class="text-5xl text-center mb-6 text-[#292929]">
Também trocar as cores, para os Tokens DaisyUI em todo o arquivo

2023-05-21 13:17 UTC, MatheusTrindade5201 requested changes
Você está quase lá! Para ter seu componente usado por todos, por favor complete as mudanças pedidas.

2023-06-30 13:06 UTC, closed without merging