[Time 248] create shortcuts section
deco-sites/fashion pull request #329
Opened 2023-05-20 22:00 UTC by llfalcao

## Qual a section que voce esta fazendo?
Shortcuts

## Links

Figma: https://www.figma.com/file/T4oBjZSaiahuqaAQA8ihls/Deco-Hackathon-III-%E2%80%A2--Blocks-Library?type=design&node-id=329-40658&t=CWaRHWzpcgOXogEh-0

Preview: https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL1Nob3J0Y3V0cy5ub3JvbmhhLnRzeA%3D%3D&type=sections

## Checklist

- [x] Estou usando tokens do DaisyUI e Tailwind CSS
- [x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [x] O componente esta editável no admin da Deco
- [x] Adicionei link de preview da section do admin da deco no PR
- [x] Minha section funciona com propriedades padrão
- [x] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:54 UTC, igorbrasileiro requested changes
Você está quase lá! Para avançar para a próxima etapa e ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-20 22:54 UTC, igorbrasileiro commented on components/footer/Footer.tsx
Remover arquivos que não faz parte da sua section

2023-05-20 22:54 UTC, igorbrasileiro commented on components/ui/Shortcuts.noronha.tsx
> +        <li class="bg-white border-2 border-solid border-[#AAAAAA] border-t-transparent flex justify-center items-center first:border-t-[#AAAAAA]">
Tem tokens hard coded

2023-05-20 22:54 UTC, igorbrasileiro commented on components/ui/Shortcuts.noronha.tsx
Mover o component4e para dentro de shortcuts.noronha.tsx

2023-05-20 23:39 UTC, llfalcao commented on components/footer/Footer.tsx
- Indentação nos componentes Footer, Modals e Features revertida para a versão da master.

2023-05-20 23:39 UTC, llfalcao commented on components/ui/Shortcuts.noronha.tsx
> +        <li class="bg-white border-2 border-solid border-[#AAAAAA] border-t-transparent flex justify-center items-center first:border-t-[#AAAAAA]">
- Cor trocada para uma predefinida do tailwind.

2023-05-20 23:40 UTC, llfalcao commented on components/ui/Shortcuts.noronha.tsx
- Movido 👍

2023-05-21 15:17 UTC, igorbrasileiro approved these changes
Bom trabalho!! 👏

2023-06-30 13:06 UTC, closed without merging