Feat/review section
deco-sites/fashion pull request #330
Opened 2023-05-20 22:00 UTC by Al3xsandro

## Qual a section que voce esta fazendo?

https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL1Jldmlldy5mcm9udEhvcnNlLnRzeA%3D%3D&type=sections

## Checklist

- [x] Estou usando tokens do DaisyUI e Tailwind CSS
- [x] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ ] O componente esta editável no admin da Deco
- [x] Adicionei link de preview da section do admin da deco no PR
- [x] Minha section funciona com propriedades padrão
- [] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:58 UTC, igorbrasileiro commented on static/deslike.png
Remover todos os arquivos que estão fora da sua section.

2023-05-20 22:58 UTC, igorbrasileiro commented on sections/Review.frontHorse.tsx
> +          Product Reviews
Texto hard coded

2023-05-20 23:01 UTC, igorbrasileiro commented
@Al3xsandro preciso do número do seu time.

2023-05-20 23:04 UTC, igorbrasileiro commented on sections/Review.frontHorse.tsx
> +                className="mask mask-star-2 bg-orange-400"
bg-orange-400 hard coded

2023-05-20 23:04 UTC, igorbrasileiro commented on sections/Review.frontHorse.tsx
> +            <span className="text-center">&nbsp; 4 stars - 238 reviews</span>
Texto hard coded

2023-05-20 23:05 UTC, igorbrasileiro commented on sections/Review.frontHorse.tsx
> +                  <img src={asset("/placeholder.png")} alt="PlaceHolder" />
Usar SVG no lugar de imagens

2023-05-20 23:05 UTC, igorbrasileiro commented on sections/Review.frontHorse.tsx
> +                    <span className="text-[#787878]">• 2 weeks ago</span>
Cor hard coded e texto também

2023-05-20 23:06 UTC, igorbrasileiro requested changes
Você está quase lá! Para avançar para a próxima etapa e ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-20 23:07 UTC, igorbrasileiro reviewed
Utilizar as props

2023-05-20 23:11 UTC, igorbrasileiro commented on sections/Auth.frontHorse.tsx
> +    <div className="relative flex min-h-screen w-full items-center justify-center bg-white md:bg-[#0000001a]">
token hard coded

2023-05-20 23:11 UTC, igorbrasileiro commented on sections/Auth.frontHorse.tsx
> +          <span className="text-normal text-[1rem]">Name</span>
Nome hard coded

2023-05-20 23:45 UTC, Al3xsandro commented on static/deslike.png
Igor, obrigado pelo review!
Por algum motivo nenhum svg do figma estava sendo lido, acabei trabalhando com a extensão vs share e os commits acabaram saindo todos na minha autoria.

Irei fazer novos testes

2023-05-21 01:33 UTC, Al3xsandro commented
@igorbrasileiro Como eu posso estar vendo o preview das minhas sections para correção?
infelizmente a section sumiu aqui do dashboard.
Eu preciso ficar testando a paleta de cores e tentar fazer os svgs funcionarem (por algum motivo não estavam sendo exibidos, através da mentoria me recomendaram o uso do "assert")

2023-05-21 10:32 UTC, Al3xsandro commented on sections/Review.frontHorse.tsx
> +          Product Reviews
Corrigido

2023-05-21 10:32 UTC, Al3xsandro commented on sections/Review.frontHorse.tsx
> +            <span className="text-center">&nbsp; 4 stars - 238 reviews</span>
Corrigido

2023-05-21 10:33 UTC, Al3xsandro commented on sections/Review.frontHorse.tsx
> +                    <span className="text-[#787878]">• 2 weeks ago</span>
Texto corrigido

2023-05-21 10:33 UTC, Al3xsandro commented on sections/Auth.frontHorse.tsx
> +          <span className="text-normal text-[1rem]">Name</span>
Corrigido

2023-05-21 11:44 UTC, Al3xsandro commented on sections/Review.frontHorse.tsx
> +                className="mask mask-star-2 bg-orange-400"
https://github.com/deco-sites/fashion/pull/330/commits/48b1f8f9c197f13219a9f775b8150b28186c38f9

2023-05-21 11:44 UTC, Al3xsandro commented on sections/Review.frontHorse.tsx
> +                  <img src={asset("/placeholder.png")} alt="PlaceHolder" />
https://github.com/deco-sites/fashion/pull/330/commits/cb1e4c2b16ede03a8ecd2eb00aadbcebb1fd0995

2023-05-21 11:59 UTC, Al3xsandro commented on sections/Auth.frontHorse.tsx
> +    <div className="relative flex min-h-screen w-full items-center justify-center bg-white md:bg-[#0000001a]">
https://github.com/deco-sites/fashion/pull/330/commits/6928714edbe0a353441fd48324a7a5485e0f435e

2023-05-23 12:25 UTC, igorbrasileiro commented
@tlgimenes o @Al3xsandro fez as melhorias da PR

2023-06-30 13:06 UTC, closed without merging