Time 159 - 123
deco-sites/fashion pull request #331
Opened 2023-05-20 22:00 UTC by jorgeskrtjr

## Qual a section que voce esta fazendo?

## Checklist

- [ ] Estou usando tokens do DaisyUI e Tailwind CSS
- [ ] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ ] O componente esta editável no admin da Deco
- [ ] Adicionei link de preview da section do admin da deco no PR
- [ ] Minha section funciona com propriedades padrão
- [ ] Adicionei links das variacoes do figma que fiz no PR

2023-05-20 22:06 UTC, jorgeskrtjr commented
Adicionando checklist

2023-05-21 02:04 UTC, tlgimenes requested changes
Você está quase lá! Para avançar para a próxima etapa e ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-05-21 02:04 UTC, tlgimenes commented on sections/BenefitsTitle/BenefitsTitle.123.tsx
> +export interface props {
Muito bom!

2023-05-21 02:04 UTC, tlgimenes commented on sections/CookieConsent/CookieConsent.123.tsx
> +export interface Props {
Massa!

2023-05-21 02:04 UTC, tlgimenes commented on sections/ImageGallery/imageGallery.123.tsx
> +export interface Props {
Seria legal de adicionar imagens via props. Para fazer isso, pode se basear aqui:
https://github.com/deco-sites/fashion/blob/b7eea65de4facd7527c509a97aefec3f9052d03c/components/ui/BannerCarousel.tsx#L11

2023-05-21 02:58 UTC, BrenoHenrique07 commented on sections/ImageGallery/imageGallery.123.tsx
> +export interface Props {
Muito obrigado pelo feedback, na hora da correria não pensamos kkkkkk

2023-06-30 13:06 UTC, closed without merging