[TIME 158 - KATIAU]
deco-sites/fashion pull request #335
Opened 2023-05-20 22:16 UTC by millenabalbi

## Qual a section que voce esta fazendo?

## Checklist

- [ X ] Estou usando tokens do DaisyUI e Tailwind CSS
- [ X ] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ X ] O componente esta editável no admin da Deco
- [ X ] Adicionei link de preview da section do admin da deco no PR
- [ X ] Minha section funciona com propriedades padrão
- [ X ] Adicionei links das variacoes do figma que fiz no PR

link figma - fizemos a variação 1
https://www.figma.com/file/T4oBjZSaiahuqaAQA8ihls/Deco-Hackathon-III-•--Blocks-Library?type=design&node-id=12-79260&t=S41hMRY3YQ4QdJ5M-0

Link Preview
https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL0ZBUS9GQVEuS0FUSUFVLnRzeA%3D%3D&type=FAQ

2023-05-20 22:21 UTC, lucis approved these changes

2023-05-20 22:21 UTC, lucis commented on sections/FAQ/FAQ.KATIAU.tsx
> +          Still have a question?
Deveria ser configurável também

2023-05-20 22:30 UTC, lucis commented on sections/FAQ/FAQ.KATIAU.tsx
> +            class="collapse collapse-arrow border-t border-base-300 bg-base-100 py-2"
Poderia remover essa alterações e usar as cores do DaisyUI ao invés de definir novas cores?

Assim os usuários de negócio podem trocar a cor através do Admin: https://daisyui.com/docs/colors/

![image](https://github.com/deco-sites/fashion/assets/18706156/c1fcaa6e-dda1-4f5c-8341-ab7b1a2b91f8)

2023-05-20 23:05 UTC, millenabalbi commented on sections/FAQ/FAQ.KATIAU.tsx
> +          Still have a question?
alteração feita!

2023-05-21 12:42 UTC, eduardobbrito requested changes
Você está quase lá! Para ter seu componente usado por todos os participantes do hackathon, por favor complete as mudanças pedidas.

2023-06-30 13:06 UTC, closed without merging